export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const MARK_AS_NOT_LOGGED_USER = 'MARK_AS_NOT_LOGGED_USER';

export const GET_MY_USER_REQUEST = 'GET_MY_USER_REQUEST';
export const GET_MY_USER_SUCCESS = 'GET_MY_USER_SUCCESS';
export const GET_MY_USER_FAILURE = 'GET_MY_USER_FAILURE';
